In [1]:
import numpy as np

# arithmetic operation

In [2]:
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)


[4 5 6 7]


In [ ]:
var1 = np.array([98,97])
var2 = np.array([92,88])
total = var1 + var2
minus = var1 - var2

print(total)
print(minus)


[190 185]
[6 9]


array([0, 0])

In [11]:
a = np.add(var1,var2)
b = np.subtract(var1,6)
c = np.multiply(var1,var2)
d = np.divide(var1,var2)
e = np.mod(var1,var2)
f = np.power(var1 , 2)
g = np.reciprocal(var1)


print(a,b,c,d,e,f,g)

[190 185] [92 91] [9016 8536] [1.06521739 1.10227273] [6 9] [9604 9409] [0 0]


# 2D array

In [12]:
arr1 = np.array([[1,2,3,4] , [5,6,7,8]])
arr2 = np.array([[1,2,3,4] , [5,6,7,8]])
t = arr1 + arr2
print(t)

[[ 2  4  6  8]
 [10 12 14 16]]


# other function

In [20]:
arr3 = np.array([11,2,3,78,89,86])
print(np.max(arr3))
print(np.min(arr3))
print(np.argmax(arr3))
print(np.argmin(arr3))
print(np.sqrt(arr3))



print(np.sin(arr3))


print(np.cumsum(arr3))



89
2
4
1
[3.31662479 1.41421356 1.73205081 8.83176087 9.43398113 9.2736185 ]
[-0.99999021  0.90929743  0.14112001  0.51397846  0.86006941 -0.92345845]
[ 11  13  16  94 183 269]


In [17]:
arr4 = np.array([[98,97,92] , [37,35,36]])
print(np.max(arr4,axis=0))
print(np.max(arr4,axis=1))


[98 97 92]
[98 37]
