# broadcasting

In [1]:
import numpy as np

In [3]:
var1 = np.array([1,2,3])
var2 = np.array([[1], [2] , [3]])
print(np.shape(var1))
print(np.shape(var2))


print(var1 + var2)


(3,)
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [7]:
arr1 = np.array([[2] , [5]])
arr2 = np.array([[2,4,8] , [5,10,20]])
print(np.shape(arr1))
print(np.shape(arr2))

print(arr1 + arr2)


(2, 1)
(2, 3)
[[ 4  6 10]
 [10 15 25]]
