In [3]:
import numpy as np

# zeros

In [5]:
ar_z = np.zeros(4)
ar_z1 = np.zeros((4,4))
print(ar_z)
print(ar_z1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# all elements be one in matrix

In [6]:
ar_1 = np.ones((3,4))
print(ar_1) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# empty array 

In [7]:
ar_2 = np.empty(5)
print(ar_2)

[0.00000000e+000 1.22000425e-311 1.22002498e-311 1.22000425e-311
 0.00000000e+000]


# range function

In [10]:
ar_3 = np.arange(1,4,2)
ar_3

array([1, 3])

# diagonal array using   {eye} function

In [16]:
ar_4 = np.eye(4)
ar_5 = np.eye(3,5)
ar_4
ar_5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

# linespace that use in n part of value range

In [22]:
ar_6 = np.linspace(0,20,num=10)
ar_6

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])