# indexing

In [5]:
import numpy as np

In [9]:
var = np.array([[1,2],[2,3]])
print(var[0])
print(var[0][0])

# in three dimensional array
var1 = np.array([[[1,7],[2,8]]])
print(var1[0,1,1])

[1 2]
1
8


# Slicing

In [14]:
# in one dimension array
arr = np.array([4,6,8,10,12])
print(arr[1:5])
print(arr[0: :2])
print(arr[::-1])

[ 6  8 10 12]
[ 4  8 12]
[12 10  8  6  4]


In [21]:
# in multi dimension
arr1 = np.array([[1,4,9,16] , [1,8,27,64]])
print(arr1[0 , ::2])

arr2 =  np.array([[[1,5,7] , [2,10,14] , [3,15,21]]])
print(arr2[0,1, ::2 ])

[1 9]
[ 2 14]
