# join 

In [ ]:
import numpy as np

# axis = 0 : column side
# axis = 1 : row side

In [ ]:
# join  using  concatinate function
# for one dimension
var = np.array([1,2,3,4])
var1 = np.array([1,4,9,16])
arr = np.concatenate((var,var1))
print(arr)


[ 1  2  3  4  1  4  9 16]


In [10]:
# for two dimension array
vr = np.array([[1,2] , [1,4]])
vr1 = np.array([[3,4] , [9,16]])
print(vr)
print()
print(vr1)
print()
ar = np.concatenate((vr,vr1),axis = 0)
ar1 = np.concatenate((vr,vr1),axis = 1)
print(ar)
print()
print(ar1)

[[1 2]
 [1 4]]

[[ 3  4]
 [ 9 16]]

[[ 1  2]
 [ 1  4]
 [ 3  4]
 [ 9 16]]

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [18]:
# using stack function one dimensional array to two dimensional array
va = np.array([1,2,3,4])
va1 = np.array([1,4,9,16])
a = np.stack((var,var1),axis = 0)
b = np.stack((var,var1),axis = 1)
print(a)
print()
print(b)
print()

# using shortcut method
c = np.hstack((var,var1)) # row
d = np.vstack((var,var1)) #column
e = np.dstack((var,var1)) #height
print(c)
print()
print(d)
print()
print(e)



[[ 1  2  3  4]
 [ 1  4  9 16]]

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]

[ 1  2  3  4  1  4  9 16]

[[ 1  2  3  4]
 [ 1  4  9 16]]

[[[ 1  1]
  [ 2  4]
  [ 3  9]
  [ 4 16]]]
