In [1]:
import numpy as np

# shuffle

In [ ]:
# shuffling the all elements in rendomly
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[2 4 5 3 1]


# unique

In [6]:
var1 = np.array([1,2,3,4,2,5,7,1,3,7,8,2])
x = np.unique(var1,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 7, 8]), array([ 0,  1,  2,  3,  5,  6, 10]), array([2, 3, 2, 1, 1, 2, 1]))


# Resize

In [ ]:
var2 = np.array([1,2,3,4,5,6])
y = np.resize(var2,(3,2))
z = np.resize(var2,(6,1))
print(y)
print()
print(z)

[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# flatten and ravel

In [10]:
# flatten convert two dimensional array to one dimensional array
# y and z is two dimensional array
print(y.flatten())
print(z.flatten())


print(y.ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
