# create numpy array with random function

* 1 . rand() function that used to generate random value between 0 to 1 

In [4]:
import numpy as np 

In [5]:
var = np.random.rand(5)
var

array([0.26980416, 0.53858373, 0.89065904, 0.97820762, 0.09869728])

In [6]:
var1 = np.random.rand(2,5)
var1

array([[0.04703008, 0.03961004, 0.04832688, 0.72538636, 0.89342396],
       [0.78493416, 0.81962873, 0.52174971, 0.0755301 , 0.1494336 ]])

*  2.randn() : used to generate close to zero   , negative avlue is also included 

In [7]:
var2 = np.random.randn(3,5)
var2

array([[ 0.09158504, -2.003128  , -2.11833225,  1.7377488 ,  0.52945085],
       [ 0.84923006,  0.65413341, -0.52958288, -0.15112035,  0.8053601 ],
       [-0.61331011, -0.21992162,  0.84002569,  1.06570698, -0.56500909]])

* 3 . ranf() that value is in interval [0.0,1.0)

In [9]:
var3 = np.random.ranf(5)
var3

array([0.7987651 , 0.00843766, 0.60670006, 0.84054707, 0.74917469])

*  4.randit() : used for given range      and randint(min_value , max_value , total_num_of_value)

In [16]:
var4 = np.random.randint(5,20,5)
var4

array([16,  6, 15, 18, 10], dtype=int32)