In [1]:
import numpy as np

# shape in numpy

In [5]:
arr = np.array([[1,2,3,4] , [3,4,8,9]])
arr.shape

(2, 4)

# for multi dimension array    using function {{ndmin}}

In [9]:
arr1 = np.array([1,3,5,7],ndmin=5)
print(arr1)
print(arr1.ndim)

print(arr1.shape)

[[[[[1 3 5 7]]]]]
5
(1, 1, 1, 1, 4)


* Here (1,1,1,1) is number of raws and (4) is number of column

# reshape

In [14]:
arr2 = np.array([1,2,3,4,56,6])
x = arr2.reshape(2,3)
print(x)
print(arr2.ndim)
print(x.ndim)

[[ 1  2  3]
 [ 4 56  6]]
1
2
