# split

In [ ]:
import numpy as np

In [ ]:
var = np.array([1,2,3,4,5,6,7])
print(var)
print()
ar = np.array_split(var,2)
ar1 = np.array_split(var,4)
ar2 = np.array_split(var,5)
print(ar)
print(ar1)
print(ar2)
print(ar[0])
print(ar1[1])


[1 2 3 4 5 6 7]

[array([1, 2, 3, 4]), array([5, 6, 7])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7])]
[array([1, 2]), array([3, 4]), array([5]), array([6]), array([7])]
[1 2 3 4]
[3 4]


In [ ]:
var1 = np.array([[1,2],[3,4],[5,6]])
print(var1)
print()
ar3 = np.array_split(var1,2)
ar4 = np.array_split(var1,2,axis = 1)
print(ar3)
print(ar4)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]
